using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace ContactManagerApp.Services
{
    public class LocalizationManager : INotifyPropertyChanged
    {
        private static readonly LocalizationManager _instance = new LocalizationManager();
        public static LocalizationManager Instance => _instance;

        private string _currentLanguage = "uk";
        private readonly Dictionary<string, Dictionary<string, string>> _translations;

        public event PropertyChangedEventHandler PropertyChanged;
        public static event EventHandler LanguageChanged;

        public static string CurrentLanguage
        {
            get => _instance._currentLanguage;
            set
            {
                if (_instance._currentLanguage != value)
                {
                    _instance._currentLanguage = value;
                    _instance.OnPropertyChanged(nameof(CurrentLanguage));
                    LanguageChanged?.Invoke(null, EventArgs.Empty);
                }
            }
        }

        private LocalizationManager()
        {
            _translations = new Dictionary<string, Dictionary<string, string>>
            {
                ["uk"] = new Dictionary<string, string>
                {
                    ["CreateContact"] = "Створити контакт",
                    ["Contacts"] = "Контакти",
                    ["Selected"] = "Вибрані",
                    ["Frequent"] = "Часті",
                    ["Password2"] = "Password",
                    ["FindDuplicate"] = "Пошук дублікатів",
                    ["Basket"] = "Кошик",
                    ["Settings"] = "Налаштування",
                    ["Organization"] = "Упорядкування",
                    ["FavouriteContacts"] = "Вибрані контакти",
                    ["LoginHeader"] = "Вхід в систему",
                    ["Login"] = "Логін",
                    ["Password"] = "Пароль",
                    ["LoginButton"] = "Увійти",
                    ["RegisterHeader"] = "Реєстрація",
                    ["RegisterButton"] = "Зареєструватися",
                    ["UserExistsError"] = "Користувач з таким логіном уже існує",
                    ["InvalidCredentialsError"] = "Неправильний логін або пароль",
                    ["Language"] = "Мова",
                    ["DeleteAccountSuccess"] = "Акаунт успішно видалено",
                    ["Theme"] = "Тема",
                    ["User"] = "Користувач",
                    ["LightTheme"] = "Світла тема",
                    ["DarkTheme"] = "Темна тема",
                    ["HighContrastTheme"] = "Контрастна тема",
                    ["English"] = "Англійська",
                    ["Ukrainian"] = "Українська",
                    ["Edit"] = "Редагувати",
                    ["AddContact"] = "Додати контакт",
                    ["Save"] = "Зберегти",
                    ["Cancel"] = "Скасувати",
                    ["ChangePhoto"] = "Змінити зображення",
                    ["RemovePhoto"] = "Вилучити зображення",
                    ["Name"] = "Ім’я",
                    ["Surname"] = "Прізвище",
                    ["Company"] = "Компанія",
                    ["Address"] = "Адреса",
                    ["Photo"] = "Фото",
                    ["IsFavourite"] = "Вибране",
                    ["Day"] = "День",
                    ["Month"] = "Місяць",
                    ["Website"] = "Веб-сайт",
                    ["Relationship"] = "Зв’язок",
                    ["CustomField"] = "Спеціальне поле",
                    ["Notes"] = "Примітки",
                    ["AddPhoneNumber"] = " Додати номер телефону",
                    ["AddEmail"] = " Додати ел. пошту",
                    ["Phone"] = "Телефон",
                    ["Initials"] = "Ініціали",
                    ["Labels"] = "Мітки",
                    ["Email"] = "Ел. пошта",
                    ["PhoneTypeMobile"] = "Мобільний",
                    ["PhoneTypeWork"] = "Робочий",
                    ["PhoneTypeHome"] = "Домашній",
                    ["PhoneTypeOther"] = "Інший",
                    ["EmailTypePersonal"] = "Особистий",
                    ["EmailTypeWork"] = "Робочий",
                    ["EmailTypeOther"] = "Інший",
                    ["RelationshipFriend"] = "Друг",
                    ["RelationshipColleague"] = "Колега",
                    ["RelationshipFamily"] = "Сім’я",
                    ["RelationshipOther"] = "Інший",
                    ["None"] = "Немає",
                    ["January"] = "Січня",
                    ["February"] = "Лютого",
                    ["March"] = "Березня",
                    ["April"] = "Квітня",
                    ["May"] = "Травня",
                    ["June"] = "Червня",
                    ["July"] = "Липня",
                    ["August"] = "Серпня",
                    ["September"] = "Вересня",
                    ["October"] = "Жовтня",
                    ["November"] = "Листопада",
                    ["December"] = "Грудня",
                    ["Back"] = "Назад",
                    ["ContactInfo"] = "Контактна інформація",
                    ["History"] = "Історія",
                    ["CreatedDateLabel"] = "Додано до списку контактів • {0:dd MMMM yyyy}р.",
                    ["UpdatedDateLabel"] = "Останнє оновлення • {0:dd MMMM yyyy}р.",
                    ["CreatedDate"] = "Дата створення",
                    ["UpdatedDate"] = "Дата оновлення",
                    ["ToggleFavourite"] = "Перемкнути Вибране",
                    ["ConfirmDeleteMessage"] = "Ви впевнені, що хочете видалити цей контакт?",
                    ["ConfirmPermanentDeleteMessage"] = "Цей контакт буде остаточно видалено без можливості відновлення. Ви впевнені?",
                    ["ConfirmDeleteTitle"] = "Підтвердження видалення",
                    ["DeletionDate"] = "Дата видалення",
                    ["Today"] = "Сьогодні",
                    ["Yesterday"] = "Вчора",
                    ["Separator"] = "о",
                    ["ViewButtonText"] = "Переглянути",
                    ["SaveContactError"] = "Помилка при збереженні контакту: {0}",
                    ["ContactNotFoundError"] = "Контакт з Id {0} не знайдено",
                    ["LoadContactsError"] = "Помилка при читанні контактів: {0}",
                    ["SaveContactsError"] = "Помилка при збереженні контактів: {0}",
                    ["LoadUsersError"] = "Помилка при зчитуванні файлу користувачів: {0}",
                    ["SaveUsersError"] = "Помилка при записі файлу користувачів: {0}",
                    ["LoadSettingsError"] = "Помилка при читанні налаштувань: {0}",
                    ["SaveSettingsError"] = "Помилка при збереженні налаштувань: {0}",
                    ["NameCannotBeEmptyError"] = "Ім'я контакту не може бути порожнім",
                    ["InvalidEmailError"] = "Невірний формат ел. пошти: {0}",
                    ["Error"] = "Помилка",
                    ["DeleteContact"] = "Видалити контакт",
                    ["Delete"] = "Видалити",
                    ["Restore"] = "Відновити",
                    ["DeletePermanently"] = "Видалити назавжди",
                    ["SelectAll"] = "Вибрати все",
                    ["ClearSelection"] = "Скасувати виділення",
                    ["MergeDuplicatesHeader"] = "Об'єднайте дубльовані контакти",
                    ["MergeAllButton"] = "Об'єднати все",
                    ["NoDuplicatesMessage"] = "Немає нових пропозицій",
                    ["MergeButton"] = "Об'єднати",
                    ["ChangePassword"] = "Змінити пароль",
                    ["NewPassword"] = "Новий пароль",
                    ["OldPassword"] = "Старий пароль",
                    ["ConfirmNewPassword"] = "Підтвердити новий пароль",
                    ["SavePassword"] = "Зберегти пароль",
                    ["DeleteAccount"] = "Видалити акаунт",
                    ["DeleteAccountConfirmation"] = "Ви впевнені, що хочете видалити свій акаунт? Цю дію неможливо скасувати.",
                    ["AllFieldsRequired"] = "Усі поля обов’язкові.",
                    ["PasswordMinLength"] = "Пароль має містити мінімум 8 символів.",
                    ["PasswordsDoNotMatch"] = "Новий пароль і підтвердження не збігаються.",
                    ["UserNotFound"] = "Користувача не знайдено.",
                    ["OldPasswordIncorrect"] = "Старий пароль введено неправильно.",
                    ["PasswordChangedSuccess"] = "Пароль успішно змінено!",
                    ["DeleteAccountFailed"] = "Не вдалося видалити акаунт.",
                    ["Logout"] = "Вихід",
                    ["ConfirmDeleteTitle"] = "Підтвердження видалення",
                    ["ConfirmDeleteMessage"] = "Видалити з контактів?",
                    ["ConfirmMoveToBasketMessage"] = "Цей контакт буде видалено з списку контактів і буде переміщено в кошик.",
                    ["MoveToBasket"] = "Перемістити в кошик",
                    ["Cancel"] = "Скасувати",
                    ["FavouriteConfirmDeleteTitle"] = "Видалити з улюблених?",
                    ["FavouriteConfirmDeleteMessage"] = "Цей контакт буде видалено з улюблених і переміщено в кошик.",
                    ["DeleteContactTitle"] = "Видалити з контактів?",
                    ["DeleteContactMessage"] = "Цей контакт буде переміщено в кошик з можливістю подальшого відновлення.",
                    ["PermanentlyDeleteTitle"] = "Видалити назавжди?",
                    ["PermanentlyDeleteMessage"] = "Цю дію не можна скасувати",
                    ["Welcome"] = "Ласкаво просимо",
                    ["Username"] = "Ім'я користувача",
                    ["Password"] = "Пароль",
                    ["RememberMe"] = "Запам’ятати мене",
                    ["LoginButton"] = "Увійти",
                    ["NoAccountPrompt"] = "Ще немає акаунта?",
                    ["SignUpButton"] = "Зареєструватися",
                    ["EmptyFieldsError"] = "Усі поля обов’язкові.",
                    ["UserIdEmptyError"] = "Помилка: UserId порожній",
                    ["LoginSuccess"] = "Успішний вхід!",
                    ["InvalidCredentialsError"] = "Неправильний логін або пароль",
                    ["CreateAccount"] = "Створити акаунт",
                    ["RegisterButton"] = "Зареєструватися",
                    ["AlreadyHaveAccount"] = "Вже маєте акаунт?",
                    ["SignInButton"] = "Увійти",
                    ["LoginAfterRegistrationError"] = "Помилка: Не вдалося увійти після реєстрації",
                    ["RegistrationSuccess"] = "Реєстрація успішна!",
                    ["RegistrationFailed"] = "Реєстрація не вдалася. Спробуйте ще раз.",
                    ["OK"] = "Ок",
                    ["Success"] = "Успіх",
                    ["ThemeApplicationError"] = "Помилка при застосуванні теми: {0}",
                    ["PhotoUploadError"] = "Помилка завантаження фото: {0}",
                    ["Yes"] = "Так",
                    ["No"] = "Ні",
                    ["PhotoDeleteError"] = "Помилка видалення фото: {0}",
                    ["TempPhotoDeleteError"] = "Помилка видалення тимчасового фото: {0}",
                    ["SearchPlaceholder"] = "Пошук",
                    ["LogoutConfirmationTitle"] = "Вийти з акаунта?",
                    ["LogoutConfirmationMessage"] = "Ви впевнені, що хочете завершити сеанс?",
                    ["SessionExpired"] = "Ваша сесія закінчилася. Введіть пароль для продовження.",
                    ["UserIdEmptyError"] = "Помилка: UserId порожній",
                    ["SaveProfile"] = "Зберегти профіль",
                    ["ProfileUpdatedSuccess"] = "Профіль успішно оновлено.",
                    ["InvalidEmailFormat"] = "Невірний формат email.",
                    ["ProfileUpdateFailed"] = "Не вдалося оновити профіль.",
                    ["InvalidImageFormat"] = "Невірний формат зображення",
                    ["PhotoSaveFailed"] = "Не вдалося зберегти фото.",
                    ["UnsavedChangesTitle"] = "Незбережені зміни",
                    ["UnsavedChangesMessage"] = "Ви маєте незбережені зміни. Бажаєте зберегти перед виходом?",
                    ["PhoneNumberFoundTitle"] = "Номер телефону знайдено",
                    ["PhoneNumberFoundMessage"] = "Цей номер телефону ({0}) уже зареєстровано в системі. Чи бажаєте автоматично заповнити дані?",
                    ["HasProfilePhoto"] = "Є фото профілю",
                    ["NoProfilePhoto"] = "Фото профілю відсутнє"
                },
                ["en"] = new Dictionary<string, string>
                {
                    ["CreateContact"] = "Create Contact",
                    ["Contacts"] = "Contacts",
                    ["Selected"] = "Selected",
                    ["Frequent"] = "Frequent",
                    ["Password2"] = "dds",
                    ["FindDuplicate"] = "Find Duplicates",
                    ["Basket"] = "Trash",
                    ["Settings"] = "Settings",
                    ["Organization"] = "Organization",
                    ["FavouriteContacts"] = "Selected contacts",
                    ["LoginHeader"] = "Sign In",
                    ["Login"] = "Login",
                    ["Password"] = "Password",
                    ["LoginButton"] = "Sign In",
                    ["RegisterHeader"] = "Register",
                    ["RegisterButton"] = "Register",
                    ["UserExistsError"] = "User with this login already exists",
                    ["InvalidCredentialsError"] = "Invalid login or password",
                    ["Language"] = "Language",
                    ["DeleteAccountSuccess"] = "Delete account success",
                    ["Theme"] = "Theme",
                    ["User"] = "User",
                    ["LightTheme"] = "Light Theme",
                    ["DarkTheme"] = "Dark Theme",
                    ["HighContrastTheme"] = "High Contrast Theme",
                    ["English"] = "English",
                    ["Ukrainian"] = "Ukrainian",
                    ["Edit"] = "Edit",
                    ["AddContact"] = "Add contact",
                    ["Save"] = "Save",
                    ["Cancel"] = "Cancel",
                    ["ChangePhoto"] = "Change picture",
                    ["RemovePhoto"] = "Remove picture",
                    ["Name"] = "Name",
                    ["Surname"] = "Surname",
                    ["Company"] = "Company",
                    ["Address"] = "Address",
                    ["Photo"] = "Photo",
                    ["IsFavourite"] = "Favorite",
                    ["Day"] = "Day",
                    ["Month"] = "Month",
                    ["Website"] = "Website",
                    ["Relationship"] = "Relationship",
                    ["CustomField"] = "Custom Field",
                    ["Notes"] = "Notes",
                    ["AddPhoneNumber"] = "+ Add phone number",
                    ["AddEmail"] = "+ Add email",
                    ["Phone"] = "Phone",
                    ["Initials"] = "Initials",
                    ["Labels"] = "Labels",
                    ["Email"] = "Email",
                    ["PhoneTypeMobile"] = "Mobile",
                    ["PhoneTypeWork"] = "Work",
                    ["PhoneTypeHome"] = "Home",
                    ["PhoneTypeOther"] = "Other",
                    ["EmailTypePersonal"] = "Personal",
                    ["EmailTypeWork"] = "Work",
                    ["EmailTypeOther"] = "Other",
                    ["RelationshipFriend"] = "Friend",
                    ["RelationshipColleague"] = "Colleague",
                    ["RelationshipFamily"] = "Family",
                    ["RelationshipOther"] = "Other",
                    ["None"] = "None",
                    ["January"] = "January",
                    ["February"] = "February",
                    ["March"] = "March",
                    ["April"] = "April",
                    ["May"] = "May",
                    ["June"] = "June",
                    ["July"] = "July",
                    ["August"] = "August",
                    ["September"] = "September",
                    ["October"] = "October",
                    ["November"] = "November",
                    ["December"] = "December",
                    ["Back"] = "Back",
                    ["ContactInfo"] = "Contact Info",
                    ["History"] = "History",
                    ["CreatedDateLabel"] = "Added to contact list • {0:dd MMMM yyyy} year",
                    ["UpdatedDateLabel"] = "Last updated • {0:dd MMMM yyyy} year",
                    ["CreatedDate"] = "Created Date",
                    ["UpdatedDate"] = "Updated Date",
                    ["ToggleFavourite"] = "Toggle Favorite",
                    ["ConfirmDeleteMessage"] = "Are you sure you want to delete this contact?",
                    ["ConfirmPermanentDeleteMessage"] = "This contact will be permanently deleted and cannot be restored. Are you sure?",
                    ["ConfirmDeleteTitle"] = "Confirm Deletion",
                    ["DeletionDate"] = "Deletion date",
                    ["Today"] = "Today",
                    ["Yesterday"] = "Yesterday",
                    ["Separator"] = "at",
                    ["ViewButtonText"] = "View",
                    ["SaveContactError"] = "Error saving contact: {0}",
                    ["ContactNotFoundError"] = "Contact with Id {0} not found",
                    ["LoadContactsError"] = "Error loading contacts: {0}",
                    ["SaveContactsError"] = "Error saving contacts: {0}",
                    ["LoadUsersError"] = "Error reading users file: {0}",
                    ["SaveUsersError"] = "Error writing users file: {0}",
                    ["LoadSettingsError"] = "Error loading settings: {0}",
                    ["SaveSettingsError"] = "Error saving settings: {0}",
                    ["NameCannotBeEmptyError"] = "Contact name cannot be empty",
                    ["InvalidEmailError"] = "Invalid email format: {0}",
                    ["Error"] = "Error",
                    ["DeleteContact"] = "Delete Contact",
                    ["Delete"] = "Delete",
                    ["Restore"] = "Restore",
                    ["DeletePermanently"] = "Delete permanently",
                    ["SelectAll"] = "Select all",
                    ["ClearSelection"] = "Clear selection",
                    ["MergeDuplicatesHeader"] = "Merge duplicate contacts",
                    ["MergeAllButton"] = "Merge All",
                    ["NoDuplicatesMessage"] = "No new suggestions",
                    ["MergeButton"] = "Merge",
                    ["ChangePassword"] = "Change Password",
                    ["NewPassword"] = "New Password",
                    ["OldPassword"] = "Password",
                    ["ConfirmNewPassword"] = "Confirm New Password",
                    ["SavePassword"] = "Save Password",
                    ["DeleteAccount"] = "Delete Account",
                    ["DeleteAccountConfirmation"] = "Are you sure you want to delete your account? This action cannot be undone.",
                    ["AllFieldsRequired"] = "All fields are required.",
                    ["PasswordMinLength"] = "Password must be at least 8 characters long.",
                    ["PasswordsDoNotMatch"] = "New password and confirmation do not match.",
                    ["UserNotFound"] = "User not found.",
                    ["OldPasswordIncorrect"] = "Old password is incorrect.",
                    ["PasswordChangedSuccess"] = "Password changed successfully!",
                    ["DeleteAccountFailed"] = "Failed to delete account.",
                    ["Logout"] = "Logout",
                    ["ConfirmDeleteTitle"] = "Confirm Deletion",
                    ["ConfirmDeleteMessage"] = "Remove from contacts?",
                    ["ConfirmMoveToBasketMessage"] = "This contact will be removed from the contact list and moved to the trash.",
                    ["MoveToBasket"] = "Move to Trash",
                    ["Cancel"] = "Cancel",
                    ["FavouriteConfirmDeleteTitle"] = "Remove from Favorites?",
                    ["FavouriteConfirmDeleteMessage"] = "This contact will be removed from favorites and moved to the trash.",
                    ["DeleteContactTitle"] = "Remove from Contacts?",
                    ["DeleteContactMessage"] = "This contact will be moved to the trash with the option to restore later.",
                    ["PermanentlyDeleteTitle"] = "Delete Permanently?",
                    ["PermanentlyDeleteMessage"] = "This action cannot be undone",
                    ["Welcome"] = "Welcome",
                    ["Username"] = "Username",
                    ["Password"] = "Password",
                    ["RememberMe"] = "Remember Me",
                    ["LoginButton"] = "Login",
                    ["NoAccountPrompt"] = "Don't have an account yet?",
                    ["SignUpButton"] = "Sign up",
                    ["EmptyFieldsError"] = "All fields are required.",
                    ["UserIdEmptyError"] = "Error: UserId is empty",
                    ["LoginSuccess"] = "Login successful!",
                    ["CreateAccount"] = "Create an account",
                    ["RegisterButton"] = "Register",
                    ["AlreadyHaveAccount"] = "Already have an account?",
                    ["SignInButton"] = "Sign in",
                    ["LoginAfterRegistrationError"] = "Error: Failed to log in after registration",
                    ["RegistrationSuccess"] = "Registration successful!",
                    ["RegistrationFailed"] = "Registration failed. Please try again.",
                    ["OK"] = "OK",
                    ["Success"] = "Success",
                    ["ThemeApplicationError"] = "Error applying theme: {0}",
                    ["PhotoUploadError"] = "Error uploading photo: {0}",
                    ["Yes"] = "Yes",
                    ["No"] = "No",
                    ["PhotoDeleteError"] = "Error deleting photo: {0}",
                    ["TempPhotoDeleteError"] = "Error deleting temporary photo: {0}",
                    ["SearchPlaceholder"] = "Search",
                    ["LogoutConfirmationTitle"] = "Log Out?",
                    ["LogoutConfirmationMessage"] = "Are you sure you want to end your session?",
                    ["SessionExpired"] = "Your session has expired. Please enter your password to continue.",
                    ["UserIdEmptyError"] = "Error: UserId is empty",
                    ["SaveProfile"] = "Save profile",
                    ["ProfileUpdatedSuccess"] = "Profile updated success",
                    ["InvalidEmailFormat"] = "Invalid email format",
                    ["ProfileUpdateFailed"] = "Profile update failed",
                    ["InvalidImageFormat"] = "Invalid image format",
                    ["PhotoSaveFailed"] = "Photo save failed",
                    ["UnsavedChangesTitle"] = "Unsaved Changes",
                    ["UnsavedChangesMessage"] = "You have unsaved changes. Would you like to save before leaving?",
                    ["PhoneNumberFoundTitle"] = "Phone Number Found",
                    ["PhoneNumberFoundMessage"] = "This phone number ({0}) is already registered in the system. Would you like to auto-fill the details?",
                    ["HasProfilePhoto"] = "Profile photo available",
                    ["NoProfilePhoto"] = "No profile photo"
                }
            };
        }

        public static string GetString(string key, params object[] args)
        {
            string language = _instance._currentLanguage;

            if (_instance._translations.TryGetValue(language, out var languageDict) &&
                languageDict.TryGetValue(key, out var value))
            {
                return args.Length > 0 ? string.Format(value, args) : value;
            }
            return key;
        }

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}